GET http://api.pokemondraftzone.com:9960/users/

###

GET http://api.pokemondraftzone.com/data/search?q=fly

###

GET http://api.pokemondraftzone.com:9960/data/search?q=fly

###

GET http://ec2-18-189-4-121.us-east-2.compute.amazonaws.com:9960/data/search?q=fly

###

POST http://api.pokemondraftzone.com:9960/users/
Content-Type: application/json

{
    "username": "speedyzoid",
    "password": "speedyRocks123"
}

###

DELETE http://api.pokemondraftzone.com:9960/users/658b5cf98aee3fb030033317

###

POST http://api.pokemondraftzone.com:9960/users/test
Content-Type: application/json

{
    "role": "admin"
}

###

PATCH http://api.pokemondraftzone.com:9960/users/658b5cf98aee3fb030033317
Content-Type: application/json

{
    "password": "speedyRocks12435"
}
