GET http://api.pokemondraftzone.com:9960/users/

###

GET http://api.pokemondraftzone.com:9960/users/657250a9ef2832aea1bbf51b

###

POST http://api.pokemondraftzone.com:9960/users/
Content-Type: application/json

{
    "username": "speedyzoid",
    "password": "speedyRocks123"
}

###

DELETE http://api.pokemondraftzone.com:9960/users/658b5cf98aee3fb030033317

###

POST http://api.pokemondraftzone.com:9960/users/test
Content-Type: application/json

{
    "role": "admin"
}

###

PATCH http://api.pokemondraftzone.com:9960/users/658b5cf98aee3fb030033317
Content-Type: application/json

{
    "password": "speedyRocks12435"
}
