GET http://localhost:9960/users/

###

GET http://localhost:9960/users/657250a9ef2832aea1bbf51b

###

POST http://localhost:9960/users/
Content-Type: application/json

{
    "username": "speedyzoid"
}

###

DELETE http://localhost:9960/users/657250a9ef2832aea1bbf51b