import { ModdedItemDataTable } from "@pkmn/sim";

export const Items: ModdedItemDataTable = {
  machampite: {
    name: "Machampite",
    spritenum: 578,
    megaStone: "Machamp-Mega",
    megaEvolves: "Machamp",
    num: 956,
    gen: 6,
    isNonstandard: "Past",
  },
  butterfreenite: {
    name: "Butterfreenite",
    spritenum: 592,
    megaStone: "Butterfree-Mega",
    megaEvolves: "Butterfree",
    num: 955,
    gen: 6,
    isNonstandard: "Past",
  },
  garbodorite: {
    name: "Garbodorite",
    spritenum: 614,
    megaStone: "Garbodor-Mega",
    megaEvolves: "Garbodor",
    num: 957,
    gen: 6,
    isNonstandard: "Past",
  },
  kinglerite: {
    name: "Kinglerite",
    spritenum: 583,
    megaStone: "Kingler-Mega",
    megaEvolves: "Kingler",
    num: 958,
    gen: 6,
    isNonstandard: "Past",
  },
  snorlaxite: {
    name: "Snorlaxite",
    spritenum: 616,
    megaStone: "Snorlax-Mega",
    megaEvolves: "Snorlax",
    num: 959,
    gen: 6,
    isNonstandard: "Past",
  },
  laprasite: {
    name: "Laprasite",
    spritenum: 612,
    megaStone: "Lapras-Mega",
    megaEvolves: "Lapras",
    num: 960,
    gen: 6,
    isNonstandard: "Past",
  },
  drednawite: {
    name: "Drednawite",
    spritenum: 575,
    megaStone: "Drednaw-Mega",
    megaEvolves: "Drednaw",
    num: 961,
    gen: 6,
    isNonstandard: "Past",
  },
  coalossalite: {
    name: "Coalossalite",
    spritenum: 591,
    megaStone: "Coalossal-Mega",
    megaEvolves: "Coalossal",
    num: 962,
    gen: 6,
    isNonstandard: "Past",
  },
  orbeetlite: {
    name: "Orbeetlite",
    spritenum: 587,
    megaStone: "Orbeetle-Mega",
    megaEvolves: "Orbeetle",
    num: 962,
    gen: 6,
    isNonstandard: "Past",
  },
  toxtricite: {
    name: "Toxtricite",
    spritenum: 582,
    megaStone: "Toxtricity-Mega",
    megaEvolves: "Toxtricity",
    num: 963,
    gen: 6,
    isNonstandard: "Past",
  },
  toxtricitelowkey: {
    name: "Toxtricite Low Key",
    spritenum: 582,
    megaStone: "Toxtricity-Low-Key-Mega",
    megaEvolves: "Toxtricity-Low-Key",
    num: 971,
    gen: 6,
    isNonstandard: "Past",
  },
  duraludonite: {
    name: "Duraludonite",
    spritenum: 577,
    megaStone: "Duraludon-Mega",
    megaEvolves: "Duraludon",
    num: 964,
    gen: 6,
    isNonstandard: "Past",
  },
  copperajahnite: {
    name: "Copperajahnite",
    spritenum: 605,
    megaStone: "Copperajah-Mega",
    megaEvolves: "Copperajah",
    num: 965,
    gen: 6,
    isNonstandard: "Past",
  },
  centiskorchite: {
    name: "Centiskorchite",
    spritenum: 586,
    megaStone: "Centiskorch-Mega",
    megaEvolves: "Centiskorch",
    num: 966,
    gen: 6,
    isNonstandard: "Past",
  },
  sandacondanite: {
    name: "Sandacondanite",
    spritenum: 626,
    megaStone: "Sandaconda-Mega",
    megaEvolves: "Sandaconda",
    num: 967,
    gen: 6,
    isNonstandard: "Past",
  },
  flapplenite: {
    name: "Flapplenite",
    spritenum: 608,
    megaStone: "Flapple-Mega",
    megaEvolves: "Flapple",
    num: 968,
    gen: 6,
    isNonstandard: "Past",
  },
  appletunite: {
    name: "Appletunite",
    spritenum: 608,
    megaStone: "Appletun-Mega",
    megaEvolves: "Appletun",
    num: 969,
    gen: 6,
    isNonstandard: "Past",
  },
  alcremienite: {
    name: "Alcremienite",
    spritenum: 620,
    megaStone: "Alcremie-Mega",
    megaEvolves: "Alcremie",
    num: 970,
    gen: 6,
    isNonstandard: "Past",
  },
};
