import type { ModdedMoveDataTable } from "@pkmn/sim";

export const Moves: ModdedMoveDataTable = {
  aquafang: {
    num: 850,
    accuracy: 100,
    basePower: 80,
    category: "Physical",
    name: "Aqua Fang",
    pp: 15,
    priority: 0,
    flags: {
      bite: 1,
      contact: 1,
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Water",
    contestType: "Tough",
  },
  darkhole: {
    num: 851,
    name: "Dark Hole",
    category: "Special",
    pp: 5,
    accuracy: 100,
    basePower: 100,
    type: "Dark",
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
    },
    target: "normal",
  },
  forbiddenspell: {
    num: 853,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Forbidden Spell",
    target: "self",
    type: "Psychic",
    flags: {},
    pp: 5,
    priority: 0,
  },
  soulrobbery: {
    num: 852,
    accuracy: 100,
    basePower: 105,
    category: "Special",
    name: "Soul Robbery",
    pp: 5,
    priority: 0,
    flags: {
      contact: 1,
      protect: 1,
      mirror: 1,
    },
    stealsBoosts: true,
    target: "normal",
    type: "Psychic",
    contestType: "Cool",
  },
};
