import type { ModdedMoveDataTable } from "@pkmn/sim";

export const Moves: ModdedMoveDataTable = {
  aquafang: {
    accuracy: 100,
    basePower: 80,
    category: "Physical",
    name: "Aqua Fang",
    pp: 15,
    priority: 0,
    flags: {
      bite: 1,
      contact: 1,
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Water",
    contestType: "Tough",
    shortDesc: "No additional effect.",
    gen: 8,
  },
  darkhole: {
    name: "Dark Hole",
    category: "Special",
    pp: 5,
    accuracy: 100,
    basePower: 100,
    type: "Dark",
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
      bypasssub: 1,
    },
    target: "normal",
    shortDesc: "40% chance to inflict sleep, bypasses substitute.",
    gen: 8,
  },
  dracobarrage: {
    accuracy: 100,
    basePower: 100,
    category: "Special",
    name: "Draco Barrage",
    pp: 5,
    priority: 0,
    num: 855,
    flags: {
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Dragon",
    desc: "This move becomes a physical attack if the user's Attack is greater than its Special Attack, including stat stage changes. If the target lost HP, the user takes recoil damage equal to 33% the HP lost by the target, rounded half up, but not less than 1 HP. This move can hit Fairy-type Pokemon.",
    shortDesc: "Physical if Atk > Sp. Atk. 33% recoil. Hits fairies.",
    gen: 8,
  },
  forbiddenspell: {
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Forbidden Spell",
    pp: 5,
    priority: 0,
    flags: {},
    target: "self",
    type: "Psychic",
    desc: "Uses of one of these 8 moves: Shell Smash, Healing Wish, Dark Hole, Tail Glow, Roar of Time, Quiver Dance, No Retreat, or Soul Robbery",
    shortDesc: "Isn't RNG fun?",
    gen: 8,
  },
  sonicslash: {
    accuracy: 100,
    basePower: 0,
    category: "Physical",
    name: "Sonic Slash",
    pp: 10,
    priority: 0,
    flags: {
      contact: 1,
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Flying",
    desc: "The power of this move depends on (user's current Speed / target's current Speed), rounded down. Power is equal to 140 if the result is 3 or more, 120 if 2, 80 if less than 2. If the target's current Speed is 0, this move's power is 80.",
    shortDesc: "140 BP if 3x target's speed; 120 BP if 2x; else 80 BP.",
    gen: 8,
  },
  soulrobbery: {
    accuracy: 100,
    basePower: 100,
    category: "Special",
    name: "Soul Robbery",
    pp: 5,
    priority: 0,
    flags: {
      contact: 1,
      protect: 1,
      mirror: 1,
      bypasssub: 1,
    },
    stealsBoosts: true,
    target: "normal",
    type: "Psychic",
    desc: "The target's stat stages greater than 0 are stolen from it and applied to the user before dealing damage.",
    shortDesc: "Steals target's boosts before dealing damage.",
    gen: 8,
  },
};
