import type { ModdedSpeciesDataTable } from "@pkmn/sim";

export const Pokedex: ModdedSpeciesDataTable = {
  butterfreemega: {
    num: 12,
    name: "Butterfree-Mega",
    baseSpecies: "Butterfree",
    forme: "Mega",
    spriteid: "Butterfree-Gmax",
    types: ["Bug", "Flying"],
    baseStats: {
      hp: 60,
      atk: 45,
      def: 100,
      spa: 140,
      spd: 100,
      spe: 80,
    },
    abilities: {
      "0": "Compound Eyes",
    },
    heightm: 17,
    weightkg: 32,
    color: "White",
    eggGroups: ["Bug"],
    requiredItem: "Butterfreenite",
  },
  machampmega: {
    num: 68,
    name: "Machamp-Mega",
    baseSpecies: "Machamp",
    forme: "Mega",
    types: ["Fighting"],
    baseStats: {
      hp: 90,
      atk: 145,
      def: 100,
      spa: 65,
      spd: 105,
      spe: 75,
    },
    abilities: {
      "0": "ORAORAORAORA",
    },
    heightm: 25,
    weightkg: 130,
    color: "Gray",
    eggGroups: ["Human-Like"],
    requiredItem: "Machampite",
  },
  kinglermega: {
    num: 99,
    name: "Kingler-Mega",
    baseSpecies: "Kingler",
    forme: "Mega",
    types: ["Water", "Steel"],
    baseStats: {
      hp: 55,
      atk: 150,
      def: 125,
      spa: 50,
      spd: 70,
      spe: 110,
    },
    abilities: {
      "0": "Tough Claws",
    },
    heightm: 19,
    weightkg: 60,
    color: "Red",
    eggGroups: ["Water 3"],
    requiredItem: "Kinglerite",
  },
  laprasmega: {
    num: 131,
    name: "Lapras-Mega",
    baseSpecies: "Lapras",
    forme: "Mega",
    types: ["Water", "Dragon"],
    baseStats: {
      hp: 130,
      atk: 105,
      def: 85,
      spa: 115,
      spd: 105,
      spe: 70,
    },
    abilities: {
      "0": "Liquid Voice",
    },
    heightm: 24,
    weightkg: 220,
    color: "Blue",
    eggGroups: ["Monster", "Water 1"],
    requiredItem: "Laprasite",
  },
  snorlaxmega: {
    num: 143,
    name: "Snorlax-Mega",
    baseSpecies: "Snorlax",
    forme: "Mega",
    types: ["Normal", "Grass"],
    baseStats: {
      hp: 160,
      atk: 160,
      def: 85,
      spa: 80,
      spd: 125,
      spe: 30,
    },
    abilities: {
      "0": "Thick Fat",
    },
    heightm: 35,
    weightkg: 460,
    color: "Black",
    eggGroups: ["Monster"],
    requiredItem: "Snorlaxite",
  },
  dialgaprimal: {
    num: 483,
    name: "Dialga-Primal",
    baseSpecies: "Dialga",
    forme: "Primal",
    types: ["Steel", "Dragon"],
    gender: "N",
    baseStats: {
      hp: 100,
      atk: 120,
      def: 150,
      spa: 185,
      spd: 130,
      spe: 90,
    },
    abilities: {
      "0": "Primal Armor",
    },
    heightm: 5.4,
    weightkg: 683,
    color: "White",
    eggGroups: ["Undiscovered"],
    requiredItem: "Adamant Orb",
  },
  garbodormega: {
    num: 569,
    name: "Garbodor-Mega",
    baseSpecies: "Garbodor",
    forme: "Mega",
    types: ["Poison"],
    baseStats: {
      hp: 80,
      atk: 135,
      def: 105,
      spa: 80,
      spd: 105,
      spe: 75,
    },
    abilities: {
      "0": "Parasitic Waste",
    },
    heightm: 21,
    weightkg: 107.3,
    color: "Green",
    eggGroups: ["Mineral"],
    requiredItem: "Garbodorite",
  },
  orbeetlemega: {
    num: 826,
    name: "Orbeetle-Mega",
    baseSpecies: "Orbeetle",
    forme: "Mega",
    types: ["Bug", "Psychic"],
    baseStats: {
      hp: 60,
      atk: 45,
      def: 115,
      spa: 135,
      spd: 120,
      spe: 95,
    },
    abilities: {
      "0": "Magic Guard",
    },
    heightm: 14,
    weightkg: 40.8,
    color: "Red",
    eggGroups: ["Bug"],
    requiredItem: "Orbeetlite",
  },
  drednawmega: {
    num: 834,
    name: "Drednaw-Mega",
    baseSpecies: "Drednaw",
    forme: "Mega",
    types: ["Water", "Fighting"],
    baseStats: {
      hp: 90,
      atk: 155,
      def: 125,
      spa: 48,
      spd: 98,
      spe: 85,
    },
    abilities: {
      "0": "Strong Jaw",
    },
    heightm: 24,
    weightkg: 115.5,
    color: "Green",
    eggGroups: ["Monster", "Water 1"],
    requiredItem: "Drednawite",
  },
  coalossalmega: {
    num: 839,
    name: "Coalossal-Mega",
    baseSpecies: "Coalossal",
    forme: "Mega",
    types: ["Steel", "Fire"],
    baseStats: {
      hp: 110,
      atk: 80,
      def: 125,
      spa: 125,
      spd: 105,
      spe: 45,
    },
    abilities: {
      "0": "Mountaineer",
    },
    heightm: 42,
    weightkg: 310.5,
    color: "Black",
    eggGroups: ["Mineral"],
    requiredItem: "Coalossalite",
  },
  flapplemega: {
    num: 841,
    name: "Flapple-Mega",
    baseSpecies: "Flapple",
    forme: "Mega",
    types: ["Grass", "Dragon"],
    baseStats: {
      hp: 70,
      atk: 145,
      def: 90,
      spa: 135,
      spd: 70,
      spe: 105,
    },
    abilities: {
      "0": "Dragon's Maw",
    },
    heightm: 24,
    weightkg: 1,
    color: "Green",
    eggGroups: ["Grass", "Dragon"],
    requiredItem: "Flapplenite",
  },
  appletunmega: {
    num: 842,
    name: "Appletun-Mega",
    baseSpecies: "Appletun",
    forme: "Mega",
    types: ["Grass", "Dragon"],
    baseStats: {
      hp: 110,
      atk: 105,
      def: 100,
      spa: 135,
      spd: 100,
      spe: 40,
    },
    abilities: {
      "0": "Contrary",
    },
    heightm: 24,
    weightkg: 13,
    color: "Green",
    eggGroups: ["Grass", "Dragon"],
    requiredItem: "Appletunite",
  },
  sandacondamega: {
    num: 844,
    name: "Sandaconda-Mega",
    baseSpecies: "Sandaconda",
    forme: "Mega",
    types: ["Ground", "Flying"],
    baseStats: {
      hp: 72,
      atk: 140,
      def: 160,
      spa: 85,
      spd: 90,
      spe: 81,
    },
    abilities: {
      "0": "Aerilate",
    },
    heightm: 22,
    weightkg: 65.5,
    color: "Green",
    eggGroups: ["Field", "Dragon"],
    requiredItem: "Sandacondanite",
  },
  toxtricitymega: {
    num: 849,
    name: "Toxtricity-Mega",
    baseSpecies: "Toxtricity",
    forme: "Mega",
    types: ["Electric", "Poison"],
    baseStats: {
      hp: 75,
      atk: 120,
      def: 80,
      spa: 155,
      spd: 80,
      spe: 111,
    },
    abilities: {
      "0": "Punk Rock",
    },
    heightm: 24,
    weightkg: 40,
    color: "Purple",
    eggGroups: ["Human-Like"],
    requiredItem: "Toxtricite",
  },
  toxtricitylowkeymega: {
    num: 849,
    name: "Toxtricity-Low-Key-Mega",
    baseSpecies: "Toxtricity-Low-Key",
    forme: "Mega",
    types: ["Electric", "Poison"],
    baseStats: {
      hp: 75,
      atk: 120,
      def: 80,
      spa: 155,
      spd: 80,
      spe: 111,
    },
    abilities: {
      "0": "Punk Rock",
    },
    heightm: 24,
    weightkg: 40,
    color: "Purple",
    eggGroups: ["Human-Like"],
    requiredItem: "Toxtricite Low Key",
  },
  centiskorchmega: {
    num: 851,
    name: "Centiskorch-Mega",
    baseSpecies: "Centiskorch",
    forme: "Mega",
    types: ["Fire", "Bug"],
    baseStats: {
      hp: 100,
      atk: 150,
      def: 80,
      spa: 90,
      spd: 110,
      spe: 85,
    },
    abilities: {
      "0": "Mountaineer",
    },
    heightm: 75,
    weightkg: 120,
    color: "Red",
    eggGroups: ["Bug"],
    requiredItem: "Centiskorchite",
  },
  alcremiemega: {
    num: 869,
    name: "Alcremie-Mega",
    baseSpecies: "Alcremie",
    forme: "Mega",
    types: ["Fairy"],
    gender: "F",
    baseStats: {
      hp: 65,
      atk: 70,
      def: 90,
      spa: 140,
      spd: 131,
      spe: 84,
    },
    abilities: {
      "0": "Self Sufficient",
    },
    heightm: 30,
    weightkg: 0.5,
    color: "White",
    eggGroups: ["Fairy", "Amorphous"],
    requiredItem: "Alcremienite",
  },
  copperajahmega: {
    num: 879,
    name: "Copperajah-Mega",
    baseSpecies: "Copperajah",
    forme: "Mega",
    types: ["Steel", "Fighting"],
    baseStats: {
      hp: 122,
      atk: 155,
      def: 94,
      spa: 100,
      spd: 94,
      spe: 20,
    },
    abilities: {
      "0": "Sheer Force",
    },
    heightm: 23,
    weightkg: 650,
    color: "Green",
    eggGroups: ["Field", "Mineral"],
    requiredItem: "Copperajahnite",
  },
  duraludonmega: {
    num: 884,
    name: "Duraludon-Mega",
    baseSpecies: "Duraludon",
    forme: "Mega",
    types: ["Steel", "Dragon"],
    baseStats: {
      hp: 70,
      atk: 95,
      def: 140,
      spa: 140,
      spd: 90,
      spe: 95,
    },
    abilities: {
      "0": "Bad Company",
    },
    heightm: 43,
    weightkg: 40,
    color: "White",
    eggGroups: ["Mineral", "Dragon"],
    requiredItem: "Duraludonite",
  },
  // tyrogunk: {
  //   num: 42069,
  //   name: "Tyrogunk",
  //   types: ["Poison", "Fighting"],
  //   baseStats: {
  //     hp: 83,
  //     atk: 96,
  //     def: 75,
  //     spa: 96,
  //     spd: 75,
  //     spe: 85,
  //   },
  //   abilities: {
  //     "0": "Prankster",
  //     "1": "Sheer Force",
  //     H: "Illusion",
  //   },
  //   heightm: 0.7,
  //   weightkg: 22,
  //   color: "Purple",
  //   eggGroups: ["Undiscovered"],
  // },
  // clefpex: {
  //   num: 14000,
  //   name: "Clefpex",
  //   types: ["Poison", "Fairy"],
  //   baseStats: {
  //     hp: 85,
  //     atk: 50,
  //     def: 100,
  //     spa: 80,
  //     spd: 105,
  //     spe: 80,
  //   },
  //   abilities: {
  //     "0": "Regenerator",
  //     "1": "Magic Guard",
  //     H: "Neutralizing Gas",
  //   },
  //   heightm: 2,
  //   weightkg: 54.5,
  //   color: "Pink",
  //   eggGroups: ["Undiscovered"],
  // },
};
