import type { ModdedSpeciesDataTable } from "@pkmn/sim";

export const Pokedex: ModdedSpeciesDataTable = {
  butterfreemega: {
    num: 12,
    name: "Butterfree-Mega",
    baseSpecies: "Butterfree",
    forme: "Mega",
    types: ["Bug", "Flying"],
    baseStats: {
      hp: 60,
      atk: 45,
      def: 100,
      spa: 140,
      spd: 100,
      spe: 80,
    },
    abilities: {
      "0": "Compound Eyes",
    },
    heightm: 17,
    weightkg: 32,
    color: "White",
    eggGroups: ["Bug"],
    requiredItem: "Butterfrite",
    gen: 8,
  },
  pikachuflying: {
    num: 25,
    name: "Pikachu-Flying",
    baseSpecies: "Pikachu",
    forme: "Flying",
    types: ["Electric", "Flying"],
    baseStats: {
      hp: 35,
      atk: 55,
      def: 40,
      spa: 50,
      spd: 50,
      spe: 90,
    },
    abilities: {
      "0": "Static",
      H: "Lightning Rod",
    },
    heightm: 0.4,
    weightkg: 6,
    color: "Yellow",
    eggGroups: ["Undiscovered"],
    gen: 8,
  },
  pikachusurfing: {
    num: 25,
    name: "Pikachu-Surfing",
    baseSpecies: "Pikachu",
    forme: "Surfing",
    types: ["Electric", "Water"],
    baseStats: {
      hp: 35,
      atk: 55,
      def: 40,
      spa: 50,
      spd: 50,
      spe: 90,
    },
    abilities: {
      "0": "Static",
      H: "Lightning Rod",
    },
    heightm: 0.4,
    weightkg: 6,
    color: "Yellow",
    eggGroups: ["Undiscovered"],
    gen: 8,
  },
  machampmega: {
    num: 68,
    name: "Machamp-Mega",
    baseSpecies: "Machamp",
    forme: "Mega",
    types: ["Fighting"],
    baseStats: {
      hp: 90,
      atk: 145,
      def: 110,
      spa: 65,
      spd: 115,
      spe: 75,
    },
    abilities: {
      "0": "ORAORAORAORA",
    },
    heightm: 25,
    weightkg: 130,
    color: "Gray",
    eggGroups: ["Human-Like"],
    requiredItem: "Machampite",
    gen: 8,
  },
  doduosevii: {
    num: 84,
    name: "Doduo-Sevii",
    baseSpecies: "Doduo",
    forme: "Sevii",
    types: ["Fire", "Ground"],
    baseStats: {
      hp: 40,
      atk: 80,
      def: 45,
      spa: 35,
      spd: 35,
      spe: 75,
    },
    abilities: {
      "0": "Rock Head",
      "1": "Early Bird",
      H: "Anger Point",
    },
    heightm: 1.4,
    weightkg: 39.2,
    color: "Brown",
    eggGroups: ["Flying"],
  },
  dodriosevii: {
    num: 85,
    name: "Dodrio-Sevii",
    baseSpecies: "Dodrio",
    forme: "Sevii",
    types: ["Fire", "Ground"],
    baseStats: {
      hp: 65,
      atk: 125,
      def: 65,
      spa: 40,
      spd: 65,
      spe: 110,
    },
    abilities: {
      "0": "Rock Head",
      "1": "Early Bird",
      H: "Anger Point",
    },
    heightm: 1.8,
    weightkg: 85.2,
    color: "Brown",
    prevo: "Doduo-Sevii",
    evoLevel: 31,
    eggGroups: ["Flying"],
  },
  kinglermega: {
    num: 99,
    name: "Kingler-Mega",
    baseSpecies: "Kingler",
    forme: "Mega",
    types: ["Water", "Steel"],
    baseStats: {
      hp: 55,
      atk: 150,
      def: 130,
      spa: 50,
      spd: 75,
      spe: 110,
    },
    abilities: {
      "0": "Tough Claws",
    },
    heightm: 19,
    weightkg: 60,
    color: "Red",
    eggGroups: ["Water 3"],
    requiredItem: "Kinglerite",
    gen: 8,
  },
  laprasmega: {
    num: 131,
    name: "Lapras-Mega",
    baseSpecies: "Lapras",
    forme: "Mega",
    types: ["Water", "Dragon"],
    baseStats: {
      hp: 130,
      atk: 105,
      def: 90,
      spa: 115,
      spd: 105,
      spe: 70,
    },
    abilities: {
      "0": "Liquid Voice",
    },
    heightm: 24,
    weightkg: 220,
    color: "Blue",
    eggGroups: ["Monster", "Water 1"],
    requiredItem: "Laprasite",
    gen: 8,
  },
  snorlaxmega: {
    num: 143,
    name: "Snorlax-Mega",
    baseSpecies: "Snorlax",
    forme: "Mega",
    types: ["Normal", "Grass"],
    baseStats: {
      hp: 160,
      atk: 160,
      def: 85,
      spa: 80,
      spd: 125,
      spe: 30,
    },
    abilities: {
      "0": "Thick Fat",
    },
    heightm: 35,
    weightkg: 460,
    color: "Black",
    eggGroups: ["Monster"],
    requiredItem: "Snorlaxite",
    gen: 8,
  },
  teddiursasevii: {
    num: 216,
    name: "Teddiursa-Sevii",
    baseSpecies: "Teddiursa",
    forme: "Sevii",
    types: ["Ghost"],
    baseStats: {
      hp: 55,
      atk: 80,
      def: 50,
      spa: 45,
      spd: 50,
      spe: 50,
    },
    abilities: {
      "0": "Pickup",
      "1": "Quick Feet",
      H: "Iron Fist",
    },
    heightm: 0.6,
    weightkg: 8.8,
    color: "Brown",
    eggGroups: ["Field"],
  },
  ursaringsevii: {
    num: 217,
    name: "Ursaring-Sevii",
    baseSpecies: "Ursaring",
    forme: "Sevii",
    types: ["Ghost", "Fighting"],
    baseStats: {
      hp: 100,
      atk: 110,
      def: 90,
      spa: 55,
      spd: 90,
      spe: 55,
    },
    abilities: {
      "0": "Guts",
      "1": "Quick Feet",
      H: "Iron Fist",
    },
    heightm: 1.8,
    weightkg: 125.8,
    color: "Brown",
    prevo: "Teddiursa-Sevii",
    evoLevel: 30,
    eggGroups: ["Field"],
  },
  mantinesevii: {
    num: 226,
    name: "Mantine-Sevii",
    baseSpecies: "Mantine",
    forme: "Sevii",
    types: ["Electric", "Poison"],
    baseStats: {
      hp: 80,
      atk: 30,
      def: 70,
      spa: 100,
      spd: 120,
      spe: 95,
    },
    abilities: {
      "0": "Static",
      "1": "Storm Drain",
      H: "Hydration",
    },
    heightm: 2.1,
    weightkg: 220,
    color: "Purple",
    prevo: "Mantyke-Sevii",
    evoType: "levelExtra",
    evoCondition: "with a Remoraid in party",
    eggGroups: ["Water 1"],
  },
  feebassevii: {
    num: 349,
    name: "Feebas-Sevii",
    forme: "Sevii",
    baseSpecies: "Feebas",
    types: ["Water", "Ground"],
    baseStats: {
      hp: 20,
      atk: 15,
      def: 20,
      spa: 10,
      spd: 55,
      spe: 80,
    },
    abilities: {
      "0": "Swift Swim",
      "1": "Oblivious",
      H: "Adaptability",
    },
    heightm: 0.6,
    weightkg: 7.4,
    color: "Brown",
    eggGroups: ["Field", "Dragon"],
  },
  miloticsevii: {
    num: 350,
    name: "Milotic-Sevii",
    forme: "Sevii",
    baseSpecies: "Milotic",
    types: ["Fairy", "Ground"],
    baseStats: {
      hp: 95,
      atk: 60,
      def: 84,
      spa: 105,
      spd: 125,
      spe: 81,
    },
    abilities: {
      "0": "Marvel Scale",
      "1": "Competitive",
      H: "Serene Grace",
    },
    heightm: 6.2,
    weightkg: 162,
    color: "Pink",
    prevo: "Feebas-Sevii",
    evoType: "useItem",
    evoItem: "Prism Scale",
    eggGroups: ["Field", "Dragon"],
  },
  carnivinesevii: {
    num: 455,
    name: "Carnivine-Sevii",
    forme: "Sevii",
    baseSpecies: "Carnivine",
    types: ["Poison", "Steel"],
    baseStats: {
      hp: 94,
      atk: 100,
      def: 92,
      spa: 55,
      spd: 77,
      spe: 36,
    },
    abilities: {
      "0": "Levitate",
    },
    heightm: 1.4,
    weightkg: 27,
    color: "Green",
    eggGroups: ["Grass"],
  },
  mantykesevii: {
    num: 458,
    name: "Mantyke-Sevii",
    baseSpecies: "Mantyke",
    forme: "Sevii",
    types: ["Electric", "Poison"],
    baseStats: {
      hp: 45,
      atk: 20,
      def: 55,
      spa: 70,
      spd: 85,
      spe: 70,
    },
    abilities: {
      "0": "Static",
      "1": "Storm Drain",
      H: "Hydration",
    },
    heightm: 1,
    weightkg: 65,
    color: "Blue",
    eggGroups: ["Undiscovered"],
  },
  dialgaprimal: {
    num: 483,
    name: "Dialga-Primal",
    baseSpecies: "Dialga",
    forme: "Primal",
    types: ["Steel", "Dragon"],
    gender: "N",
    baseStats: {
      hp: 100,
      atk: 120,
      def: 150,
      spa: 185,
      spd: 130,
      spe: 90,
    },
    abilities: {
      "0": "Primal Armor",
    },
    heightm: 5.4,
    weightkg: 683,
    color: "White",
    eggGroups: ["Undiscovered"],
    requiredItem: "Adamant Orb",
    gen: 8,
  },
  blitzlesevii: {
    num: 522,
    name: "Blitzle-Sevii",
    baseSpecies: "Blitzle",
    forme: "Sevii",
    types: ["Ice", "Electric"],
    baseStats: {
      hp: 45,
      atk: 45,
      def: 32,
      spa: 65,
      spd: 32,
      spe: 76,
    },
    abilities: {
      "0": "Lightning Rod",
      "1": "Illuminate",
      H: "Ice Body",
    },
    heightm: 0.8,
    weightkg: 29.8,
    color: "Black",
    eggGroups: ["Field"],
  },
  zebstrikasevii: {
    num: 523,
    name: "Zebstrika-Sevii",
    baseSpecies: "Zebstrika",
    forme: "Sevii",
    types: ["Ice", "Electric"],
    baseStats: {
      hp: 75,
      atk: 70,
      def: 63,
      spa: 110,
      spd: 63,
      spe: 116,
    },
    abilities: {
      "0": "Lightning Rod",
      "1": "Illuminate",
      H: "Ice Body",
    },
    heightm: 1.6,
    weightkg: 79.5,
    color: "Black",
    prevo: "Blitzle-Sevii",
    evoLevel: 27,
    eggGroups: ["Field"],
  },
  garbodormega: {
    num: 569,
    name: "Garbodor-Mega",
    baseSpecies: "Garbodor",
    forme: "Mega",
    types: ["Poison"],
    baseStats: {
      hp: 80,
      atk: 135,
      def: 105,
      spa: 105,
      spd: 105,
      spe: 75,
    },
    abilities: {
      "0": "Parasitic Waste",
    },
    heightm: 21,
    weightkg: 107.3,
    color: "Green",
    eggGroups: ["Mineral"],
    requiredItem: "Garbodorite",
    gen: 8,
  },
  claunchersevii: {
    num: 692,
    name: "Clauncher-Sevii",
    forme: "Sevii",
    baseSpecies: "Clauncher",
    types: ["Bug", "Dark"],
    baseStats: {
      hp: 50,
      atk: 38,
      def: 62,
      spa: 58,
      spd: 63,
      spe: 59,
    },
    abilities: {
      "0": "Mega Launcher",
    },
    heightm: 0.5,
    weightkg: 8.3,
    color: "Blue",
    eggGroups: ["Water 1", "Water 3"],
  },
  clawitzersevii: {
    num: 693,
    name: "Clawitzer-Sevii",
    forme: "Sevii",
    baseSpecies: "Clawitzer",
    types: ["Bug", "Dark"],
    baseStats: {
      hp: 81,
      atk: 63,
      def: 83,
      spa: 110,
      spd: 79,
      spe: 97,
    },
    abilities: {
      "0": "Mega Launcher",
    },
    heightm: 1.3,
    weightkg: 35.3,
    color: "Blue",
    prevo: "Clauncher-Sevii",
    evoLevel: 34,
    eggGroups: ["Water 1", "Water 3"],
  },
  wishiwashisevii: {
    num: 746,
    name: "Wishiwashi-Sevii",
    baseSpecies: "Wishiwashi",
    forme: "Sevii",
    types: ["Ghost"],
    baseStats: {
      hp: 60,
      atk: 20,
      def: 20,
      spa: 25,
      spd: 15,
      spe: 35,
    },
    abilities: {
      "0": "Schooling",
    },
    heightm: 0.2,
    weightkg: 0.3,
    color: "Blue",
    eggGroups: ["Water 2"],
  },
  wishiwashiseviischool: {
    num: 746,
    name: "Wishiwashi-Sevii-School",
    baseSpecies: "Wishiwashi",
    forme: "Sevii-School",
    types: ["Ghost", "Dragon"],
    baseStats: {
      hp: 60,
      atk: 140,
      def: 130,
      spa: 140,
      spd: 135,
      spe: 25,
    },
    abilities: {
      "0": "Schooling",
    },
    heightm: 8.2,
    weightkg: 78.6,
    color: "Blue",
    eggGroups: ["Water 2"],
    requiredAbility: "Schooling",
    battleOnly: "Wishiwashi-Sevii",
  },
  dhelmisesevii: {
    num: 781,
    name: "Dhelmise-Sevii",
    forme: "Sevii",
    baseSpecies: "Dhelmise",
    types: ["Water", "Grass"],
    gender: "N",
    baseStats: {
      hp: 90,
      atk: 81,
      def: 105,
      spa: 106,
      spd: 95,
      spe: 40,
    },
    abilities: {
      "0": "Sap Sipper",
      "1": "Gooey",
      H: "Tinted Lens",
    },
    heightm: 3.9,
    weightkg: 210,
    color: "Green",
    eggGroups: ["Mineral"],
  },
  orbeetlemega: {
    num: 826,
    name: "Orbeetle-Mega",
    baseSpecies: "Orbeetle",
    forme: "Mega",
    types: ["Bug", "Psychic"],
    baseStats: {
      hp: 60,
      atk: 45,
      def: 125,
      spa: 135,
      spd: 130,
      spe: 100,
    },
    abilities: {
      "0": "Magic Guard",
    },
    heightm: 0.4,
    weightkg: 40.8,
    color: "Red",
    eggGroups: ["Bug"],
    requiredItem: "Orbeetlite",
  },
  drednawmega: {
    num: 834,
    name: "Drednaw-Mega",
    baseSpecies: "Drednaw",
    forme: "Mega",
    types: ["Water", "Fighting"],
    baseStats: {
      hp: 90,
      atk: 155,
      def: 125,
      spa: 48,
      spd: 98,
      spe: 85,
    },
    abilities: {
      "0": "Strong Jaw",
    },
    heightm: 1,
    weightkg: 115.5,
    color: "Green",
    eggGroups: ["Monster", "Water 1"],
    requiredItem: "Drednawite",
  },
  coalossalmega: {
    num: 839,
    name: "Coalossal-Mega",
    baseSpecies: "Coalossal",
    forme: "Mega",
    types: ["Steel", "Fire"],
    baseStats: {
      hp: 110,
      atk: 80,
      def: 125,
      spa: 125,
      spd: 105,
      spe: 45,
    },
    abilities: {
      "0": "Mountaineer",
    },
    heightm: 2.8,
    weightkg: 310.5,
    color: "Black",
    eggGroups: ["Mineral"],
    requiredItem: "Coalossite",
  },
  flapplemega: {
    num: 841,
    name: "Flapple-Mega",
    baseSpecies: "Flapple",
    forme: "Mega",
    types: ["Grass", "Dragon"],
    baseStats: {
      hp: 70,
      atk: 145,
      def: 90,
      spa: 135,
      spd: 70,
      spe: 105,
    },
    abilities: {
      "0": "Dragon's Maw",
    },
    heightm: 0.3,
    weightkg: 1,
    color: "Green",
    eggGroups: ["Grass", "Dragon"],
    requiredItem: "Flapplite",
  },
  appletunmega: {
    num: 842,
    name: "Appletun-Mega",
    baseSpecies: "Appletun",
    forme: "Mega",
    types: ["Grass", "Dragon"],
    baseStats: {
      hp: 110,
      atk: 105,
      def: 100,
      spa: 135,
      spd: 100,
      spe: 40,
    },
    abilities: {
      "0": "Contrary",
    },
    heightm: 0.4,
    weightkg: 13,
    color: "Green",
    eggGroups: ["Grass", "Dragon"],
    requiredItem: "Appletunite",
  },
  sandacondamega: {
    num: 844,
    name: "Sandaconda-Mega",
    baseSpecies: "Sandaconda",
    forme: "Mega",
    types: ["Ground", "Flying"],
    baseStats: {
      hp: 72,
      atk: 140,
      def: 160,
      spa: 85,
      spd: 90,
      spe: 81,
    },
    abilities: {
      "0": "Aerilate",
    },
    heightm: 3.8,
    weightkg: 65.5,
    color: "Green",
    eggGroups: ["Field", "Dragon"],
    requiredItem: "Sandacondite",
  },
  toxtricitylowkeymega: {
    num: 849,
    name: "Toxtricity-Low-Key-Mega",
    baseSpecies: "Toxtricity",
    forme: "Low-Key-Mega",
    types: ["Electric", "Poison"],
    baseStats: {
      hp: 75,
      atk: 120,
      def: 80,
      spa: 155,
      spd: 80,
      spe: 111,
    },
    abilities: {
      "0": "Punk Rock",
    },
    heightm: 1.6,
    weightkg: 40,
    color: "Purple",
    eggGroups: ["Human-Like"],
    requiredItem: "Toxtricitite Low Key",
    battleOnly: "Toxtricity-Low-Key",
    isMega: true,
  },
  toxtricitymega: {
    num: 849,
    name: "Toxtricity-Mega",
    baseSpecies: "Toxtricity",
    forme: "Mega",
    types: ["Electric", "Poison"],
    baseStats: {
      hp: 75,
      atk: 120,
      def: 80,
      spa: 155,
      spd: 80,
      spe: 111,
    },
    abilities: {
      "0": "Punk Rock",
    },
    heightm: 1.6,
    weightkg: 40,
    color: "Purple",
    eggGroups: ["Human-Like"],
    requiredItem: "Toxtricitite",
  },
  sizzlipedesevii: {
    num: 850,
    name: "Sizzlipede-Sevii",
    baseSpecies: "Sizzlipede",
    forme: "Sevii",
    types: ["Ground", "Bug"],
    baseStats: {
      hp: 50,
      atk: 65,
      def: 45,
      spa: 50,
      spd: 50,
      spe: 45,
    },
    abilities: {
      "0": "Shed Skin",
      "1": "White Smoke",
      H: "Mold Breaker",
    },
    heightm: 0.7,
    weightkg: 1,
    color: "Red",
    eggGroups: ["Bug"],
  },
  centiskorchmega: {
    num: 851,
    name: "Centiskorch-Mega",
    baseSpecies: "Centiskorch",
    forme: "Mega",
    types: ["Fire", "Bug"],
    baseStats: {
      hp: 100,
      atk: 150,
      def: 80,
      spa: 90,
      spd: 110,
      spe: 85,
    },
    abilities: {
      "0": "Mountaineer",
    },
    heightm: 3,
    weightkg: 120,
    color: "Red",
    eggGroups: ["Bug"],
    requiredItem: "Centiskite",
  },
  centiskorchsevii: {
    num: 851,
    name: "Centiskorch-Sevii",
    baseSpecies: "Centiskorch",
    forme: "Sevii",
    types: ["Ground", "Bug"],
    baseStats: {
      hp: 100,
      atk: 115,
      def: 65,
      spa: 65,
      spd: 90,
      spe: 90,
    },
    abilities: {
      "0": "Shed Skin",
      "1": "White Smoke",
      H: "Mold Breaker",
    },
    heightm: 3,
    weightkg: 120,
    color: "Red",
    prevo: "Sizzlipede-Sevii",
    evoLevel: 28,
    eggGroups: ["Bug"],
  },
  centiskorchseviimega: {
    num: 851,
    name: "Centiskorch-Sevii-Mega",
    baseSpecies: "Centiskorch",
    forme: "Sevii-Mega",
    types: ["Ground", "Bug"],
    baseStats: {
      hp: 100,
      atk: 150,
      def: 80,
      spa: 75,
      spd: 100,
      spe: 120,
    },
    abilities: {
      "0": "Arena Trap",
      "1": "Sand Force",
      H: "Arena Trap",
    },
    heightm: 3,
    weightkg: 120,
    color: "Red",
    eggGroups: ["Bug"],
    requiredItem: "Centiskite Sevii",
    battleOnly: "Centiskorch-Sevii",
    isMega: true,
  },
  alcremiemega: {
    num: 869,
    name: "Alcremie-Mega",
    baseSpecies: "Alcremie",
    forme: "Mega",
    types: ["Fairy"],
    gender: "F",
    baseStats: {
      hp: 65,
      atk: 70,
      def: 90,
      spa: 140,
      spd: 131,
      spe: 84,
    },
    abilities: {
      "0": "Self Sufficient",
    },
    heightm: 0.3,
    weightkg: 0.5,
    color: "White",
    eggGroups: ["Fairy", "Amorphous"],
    requiredItem: "Alcremite",
  },
  copperajahmega: {
    num: 879,
    name: "Copperajah-Mega",
    baseSpecies: "Copperajah",
    forme: "Mega",
    types: ["Steel", "Fighting"],
    baseStats: {
      hp: 122,
      atk: 155,
      def: 94,
      spa: 100,
      spd: 94,
      spe: 20,
    },
    abilities: {
      "0": "Sheer Force",
    },
    heightm: 3,
    weightkg: 650,
    color: "Green",
    eggGroups: ["Field", "Mineral"],
    requiredItem: "Copperajite",
  },
  duraludonmega: {
    num: 884,
    name: "Duraludon-Mega",
    baseSpecies: "Duraludon",
    forme: "Mega",
    types: ["Steel", "Dragon"],
    baseStats: {
      hp: 85,
      atk: 95,
      def: 140,
      spa: 140,
      spd: 90,
      spe: 95,
    },
    abilities: {
      "0": "Bad Company",
    },
    heightm: 1.8,
    weightkg: 40,
    color: "White",
    eggGroups: ["Mineral", "Dragon"],
    requiredItem: "Duraludonite",
    isNonstandard: "Past",
  },
  nymblesevii: {
    num: 919,
    name: "Nymble-Sevii",
    baseForme: "Nymble",
    forme: "Sevii",
    types: ["Bug", "Dragon"],
    baseStats: {
      hp: 33,
      atk: 46,
      def: 40,
      spa: 21,
      spd: 25,
      spe: 45,
    },
    abilities: {
      "0": "Swarm",
      H: "Tinted Lens",
    },
    heightm: 0.2,
    weightkg: 1,
    color: "Gray",
    eggGroups: ["Bug"],
  },
  lokixsevii: {
    num: 920,
    name: "Lokix-Sevii",
    baseForme: "Lokix",
    forme: "Sevii",
    types: ["Bug", "Dragon"],
    baseStats: {
      hp: 71,
      atk: 102,
      def: 78,
      spa: 52,
      spd: 55,
      spe: 92,
    },
    abilities: {
      "0": "Swarm",
      H: "Tinted Lens",
    },
    heightm: 1,
    weightkg: 17.5,
    color: "Gray",
    prevo: "Nymble-Sevii",
    evoLevel: 24,
    eggGroups: ["Bug"],
  },
  noibatsevii: {
    num: 714,
    name: "Noibat-Sevii",
    baseSpecies: "Noibat",
    forme: "Sevii",
    types: ["Rock", "Ghost"],
    baseStats: {
      hp: 40,
      atk: 45,
      def: 35,
      spa: 30,
      spd: 40,
      spe: 55,
    },
    abilities: {
      "0": "Rock Head",
      "1": "Sturdy",
      H: "Levitate",
    },
    heightm: 0.5,
    weightkg: 8,
    color: "Purple",
    eggGroups: ["Flying", "Dragon"],
  },
  noivernsevii: {
    num: 715,
    name: "Noivern-Sevii",
    baseSpecies: "Noivern",
    forme: "Sevii",
    types: ["Rock", "Ghost"],
    baseStats: {
      hp: 85,
      atk: 102,
      def: 80,
      spa: 70,
      spd: 80,
      spe: 123,
    },
    abilities: {
      "0": "Rock Head",
      "1": "Sturdy",
      H: "Levitate",
    },
    heightm: 1.5,
    weightkg: 85,
    color: "Purple",
    prevo: "Noibat-Sevii",
    evoLevel: 48,
    eggGroups: ["Flying", "Dragon"],
  },
  toedscoolcool: {
    num: 948,
    name: "Toedscool-Cool",
    baseSpecies: "Toedscool",
    forme: "Cool",
    types: ["Ground", "Grass"],
    baseStats: {
      hp: 100,
      atk: 100,
      def: 100,
      spa: 100,
      spd: 100,
      spe: 255,
    },
    abilities: {
      "0": "Clear Body",
      "1": "Bullshit Ability",
      H: "Mold Breaker",
    },
    heightm: 0.9,
    weightkg: 33,
    color: "Yellow",
    eggGroups: ["Field"],
  },
  chillet: {
    name: "Chillet",
    types: ["Ice", "Dragon"],
    baseStats: {
      hp: 85,
      atk: 100,
      def: 74,
      spa: 45,
      spd: 65,
      spe: 111,
    },
    abilities: {
      "0": "Refrigerate",
    },
    num: -420,
    weightkg: 70,
    eggGroups: ["Dragon"],
  },
};
