import { ModdedAbilityDataTable } from "@pkmn/sim";

export const Abilities: ModdedAbilityDataTable = {
  absolution: {
    onModifySpAPriority: 5,
    name: "Absolution",
    gen: 6,
    rating: 2,
    num: 5,
  },
  amplifier: {
    onBasePowerPriority: 19,
    name: "Amplifier",
    gen: 6,
    rating: 3,
    num: 6,
  },
  ancientpresence: {
    onModifyMovePriority: -5,
    name: "Ancient Presence",
    gen: 6,
    rating: 2,
    num: 7,
  },
  athenian: {
    onModifySpAPriority: 5,
    name: "Athenian",
    gen: 6,
    rating: 5,
    num: 8,
  },
  blazeboost: {
    onBeforeMovePriority: 0.5,
    name: "Blaze Boost",
    gen: 6,
    rating: 4,
    num: 12,
  },
  chlorofury: {
    name: "Chlorofury",
    gen: 6,
    rating: 3.5,
    num: 9,
  },
  etherealshroud: {
    onSourceModifyAtkPriority: 6,
    onSourceModifySpAPriority: 6,
    name: "Ethereal Shroud",
    flags: {
      breakable: 1,
    },
    gen: 6,
    rating: 3.5,
    num: 10,
  },
  eventhorizon: {
    name: "Event Horizon",
    gen: 6,
    rating: 5,
    num: 11,
  },
  foundry: {
    onModifyTypePriority: -1,
    onBasePowerPriority: 23,
    onTryMovePriority: -2,
    name: "Foundry",
    rating: 4,
    num: 13,
  },
  glitch: {
    onDamagingHitOrder: 1,
    name: "Glitch",
    rating: 4,
    num: 24,
  },
  heliophobia: {
    name: "Heliophobia",
    gen: 6,
    rating: 2,
    num: 14,
  },
  hubris: {
    name: "Hubris",
    gen: 6,
    rating: 3.5,
    num: 15,
  },
  icecleats: {
    name: "Ice Cleats",
    rating: 3,
    num: 185,
  },
  intoxicate: {
    onModifyTypePriority: -1,
    onBasePowerPriority: 23,
    name: "Intoxicate",
    rating: 4,
    num: 16,
  },
  irrelephant: {
    name: "Irrelephant",
    gen: 6,
    rating: 3,
    num: 17,
  },
  lernean: {
    onResidualOrder: 29,
    name: "Lernean",
    gen: 6,
    rating: 4,
    num: 18,
  },
  noctem: {
    name: "Noctem",
    gen: 6,
    rating: 4.5,
    num: 19,
  },
  omnitype: {
    onTryHitPriority: 1,
    onTrapPokemonPriority: -10,
    flags: {
      breakable: 1,
    },
    name: "Omnitype",
    gen: 6,
    rating: 3,
    num: 20,
  },
  periodicorbit: {
    name: "Periodic Orbit",
    gen: 6,
    rating: 4,
    num: 23,
  },
  pendulum: {
    name: "Pendulum",
    gen: 6,
    rating: 4.5,
    num: 21,
  },
  phototroph: {
    onResidualOrder: 5,
    onResidualSubOrder: 5,
    name: "Phototroph",
    gen: 6,
    rating: 1.5,
    num: 22,
  },
  prismguard: {
    onDamagingHitOrder: 1,
    name: "Prism Guard",
    gen: 6,
    rating: 2.5,
    num: 24,
  },
  proteanmaxima: {
    onModifyAccuracyPriority: 8,
    name: "Protean Maxima",
    gen: 6,
    rating: 4.5,
    num: 25,
  },
  psychocall: {
    onModifyAtkPriority: 5,
    onModifySpAPriority: 5,
    name: "Psycho Call",
    gen: 6,
    rating: 2,
    num: 26,
  },
  regurgitation: {
    name: "Regurgitation",
    gen: 6,
    rating: 3,
    num: 27,
  },
  shadowcall: {
    onModifyAtkPriority: 5,
    onModifySpAPriority: 5,
    name: "Shadow Call",
    gen: 6,
    rating: 2,
    num: 33,
  },
  shadowdance: {
    name: "Shadow Dance",
    gen: 6,
    rating: 3,
    num: 34,
  },
  shadowsynergy: {
    onModifyAtkPriority: 5,
    onModifySpAPriority: 5,
    name: "Shadow Synergy",
    gen: 6,
    rating: 3.5,
    num: 35,
  },
  sleet: {
    name: "Sleet",
    gen: 6,
    rating: 4,
    num: 36,
  },
  spectraljaws: {
    onBasePowerPriority: 19,
    name: "Spectral Jaws",
    gen: 6,
    rating: 3,
    num: 37,
  },
  spiritcall: {
    onModifyAtkPriority: 5,
    onModifySpAPriority: 5,
    name: "Spirit Call",
    gen: 6,
    rating: 2,
    num: 38,
  },
  supercell: {
    onModifySpAPriority: 5,
    name: "Supercell",
    gen: 6,
    rating: 2,
    num: 39,
  },
  speedswap: {
    name: "Speed Swap",
    gen: 6,
    rating: 4.5,
    num: 40,
  },
  unleafed: {
    name: "Unleafed",
    gen: 6,
    rating: 2.5,
    num: 28,
  },
  vampiric: {
    name: "Vampiric",
    gen: 6,
    rating: 3.5,
    num: 29,
  },
  vaporization: {
    name: "Vaporization",
    flags: {
      breakable: 1,
    },
    gen: 6,
    rating: 3.5,
    num: 30,
  },
  venomous: {
    onModifyMovePriority: -1,
    name: "Venomous",
    gen: 6,
    rating: 2,
    num: 31,
  },
  windforce: {
    name: "Wind Force",
    flags: {
      breakable: 1,
    },
    gen: 6,
    rating: 3,
    num: 32,
  },
  winterjoy: {
    onBasePowerPriority: 21,
    name: "Winter Joy",
    gen: 6,
    rating: 3,
    num: 32,
  },
};
