import type { ModdedItemDataTable } from "@pkmn/sim";

export const Items: ModdedItemDataTable = {
  ancientball: {
    name: "Ancient Ball",
    spritenum: 752,
    num: 994,
    gen: 6,
    isPokeball: true,
  },
  bisharpite: {
    name: "Bisharpite",
    spritenum: 753,
    megaStone: { Bisharp: "Bisharp-Mega" },
    num: 992,
    gen: 6,
    isNonstandard: "Past",
  },
  cacturnite: {
    name: "Cacturnite",
    spritenum: 754,
    megaStone: { Cacturne: "Cacturne-Mega" },
    num: 938,
    gen: 6,
    isNonstandard: "Past",
  },
  chatotite: {
    name: "Chatotite",
    spritenum: 755,
    megaStone: { Chatot: "Chatot-Mega" },
    num: 939,
    gen: 6,
    isNonstandard: "Past",
  },
  crawdite: {
    name: "Crawdite",
    spritenum: 756,
    megaStone: { Crawdaunt: "Crawdaunt-Mega" },
    num: 940,
    gen: 6,
    isNonstandard: "Past",
  },
  cryogonite: {
    name: "Cryogonite",
    spritenum: 757,
    megaStone: { Cryogonal: "Cryogonal-Mega" },
    num: 941,
    gen: 6,
    isNonstandard: "Past",
  },
  crystalfragment: {
    name: "Crystal Fragment",
    spritenum: 758,
    megaStone: { "Metagross-Delta-R": "Metagross-Delta-R-Crystal" },
    num: 993,
    gen: 6,
    isNonstandard: "Past",
  },
  crystalpiece: {
    name: "Crystal Piece",
    spritenum: 759,
    num: 929,
    gen: 6,
    isNonstandard: "Past",
  },
  darkrock: {
    name: "Dark Rock",
    spritenum: 760,
    num: 927,
    gen: 6,
  },
  deltaball: {
    name: "Delta Ball",
    spritenum: 761,
    num: 995,
    gen: 6,
    isPokeball: true,
  },
  deltabisharpite: {
    name: "Delta Bisharpite",
    spritenum: 762,
    megaStone: { "Bisharp-Delta": "Bisharp-Delta-Mega" },
    num: 969,
    gen: 6,
    isNonstandard: "Past",
  },
  deltablastoisinite: {
    name: "Delta Blastoisinite",
    spritenum: 763,
    megaStone: { "Blastoise-Delta": "Blastoise-Delta-Mega" },
    num: 970,
    gen: 6,
    isNonstandard: "Past",
  },
  deltacameruptite: {
    name: "Delta Cameruptite",
    spritenum: 764,
    megaStone: { "Camerupt-Delta": "Camerupt-Delta-Mega" },
    num: 971,
    gen: 6,
    isNonstandard: "Past",
  },
  deltacharizardite: {
    name: "Delta Charizardite",
    spritenum: 765,
    megaStone: { "Charizard-Delta": "Charizard-Delta-Mega" },
    num: 972,
    gen: 6,
    isNonstandard: "Past",
  },
  deltaetigirafarigite: {
    name: "Delta Etigirafarigite",
    spritenum: 766,
    megaStone: { "Girafarig-Delta": "Girafarig-Delta-Mega" },
    num: 973,
    gen: 6,
    isNonstandard: "Past",
  },
  deltafroslassite: {
    name: "Delta Froslassite",
    spritenum: 767,
    megaStone: { "Froslass-Delta": "Froslass-Delta-Mega" },
    num: 974,
    gen: 6,
    isNonstandard: "Past",
  },
  deltagalladite: {
    name: "Delta Galladite",
    spritenum: 768,
    megaStone: { "Gallade-Delta": "Gallade-Delta-Mega" },
    num: 975,
    gen: 6,
    isNonstandard: "Past",
  },
  deltagardevoirite: {
    name: "Delta Gardevoirite",
    spritenum: 769,
    megaStone: { "Gardevoir-Delta": "Gardevoir-Delta-Mega" },
    num: 976,
    gen: 6,
    isNonstandard: "Past",
  },
  deltaglalitite: {
    name: "Delta Glalitite",
    spritenum: 770,
    megaStone: { "Glalie-Delta": "Glalie-Delta-Mega" },
    num: 977,
    gen: 6,
    isNonstandard: "Past",
  },
  deltalopunnite: {
    name: "Delta Lopunnite",
    spritenum: 771,
    megaStone: { "Lopunny-Delta": "Lopunny-Delta-Mega" },
    num: 978,
    gen: 6,
    isNonstandard: "Past",
  },
  deltalucarionite: {
    name: "Delta Lucarionite",
    spritenum: 772,
    megaStone: { "Lucario-Delta": "Lucario-Delta-Mega" },
    num: 979,
    gen: 6,
    isNonstandard: "Past",
  },
  deltamawilite: {
    name: "Delta Mawilite",
    spritenum: 773,
    megaStone: { "Mawile-Delta": "Mawile-Delta-Mega" },
    num: 980,
    gen: 6,
    isNonstandard: "Past",
  },
  deltamedichamite: {
    name: "Delta Medichamite",
    spritenum: 774,
    megaStone: { "Medicham-Delta": "Medicham-Delta-Mega" },
    num: 981,
    gen: 6,
    isNonstandard: "Past",
  },
  deltametagrossiteruin: {
    name: "Delta Metagrossite Ruin",
    spritenum: 775,
    megaStone: { "Metagross-Delta-R": "Metagross-Delta-R-Mega" },
    num: 982,
    gen: 6,
    isNonstandard: "Past",
  },
  deltametagrossitespider: {
    name: "Delta Metagrossite Spider",
    spritenum: 776,
    megaStone: { "Metagross-Delta-S": "Metagross-Delta-S-Mega" },
    num: 983,
    gen: 6,
    isNonstandard: "Past",
  },
  deltamilotite: {
    name: "Delta Milotite",
    spritenum: 777,
    megaStone: { "Milotic-Delta": "Milotic-Delta-Mega" },
    num: 984,
    gen: 6,
    isNonstandard: "Past",
  },
  deltapidgeotite: {
    name: "Delta Pidgeotite",
    spritenum: 778,
    megaStone: { "Pidgeot-Delta": "Pidgeot-Delta-Mega" },
    num: 985,
    gen: 6,
    isNonstandard: "Past",
  },
  deltasablenite: {
    name: "Delta Sablenite",
    spritenum: 779,
    megaStone: { "Sableye-Delta": "Sableye-Delta-Mega" },
    num: 986,
    gen: 6,
    isNonstandard: "Past",
  },
  deltascizorite: {
    name: "Delta Scizorite",
    spritenum: 780,
    megaStone: { "Scizor-Delta": "Scizor-Delta-Mega" },
    num: 987,
    gen: 6,
    isNonstandard: "Past",
  },
  deltasunflorite: {
    name: "Delta Sunflorite",
    spritenum: 781,
    megaStone: { "Sunflora-Delta": "Sunflora-Delta-Mega" },
    num: 988,
    gen: 6,
    isNonstandard: "Past",
  },
  deltatyphlosionite: {
    name: "Delta Typhlosionite",
    spritenum: 782,
    megaStone: { "Typhlosion-Delta": "Typhlosion-Delta-Mega" },
    num: 989,
    gen: 6,
    isNonstandard: "Past",
  },
  deltavenusaurite: {
    name: "Delta Venusaurite",
    spritenum: 783,
    megaStone: { "Venusaur-Delta": "Venusaur-Delta-Mega" },
    num: 990,
    gen: 6,
    isNonstandard: "Past",
  },
  donphanite: {
    name: "Donphanite",
    spritenum: 784,
    megaStone: { Donphan: "Donphan-Mega" },
    num: 965,
    gen: 6,
    isNonstandard: "Past",
  },
  eevite: {
    name: "Eevite",
    spritenum: 785,
    megaStone: { "Eevee-Pre-Mega": "Eevee-Mega-Base" },
    num: 973,
    gen: 6,
    isNonstandard: "Past",
  },
  etigirafarigite: {
    name: "Etigirafarigite",
    spritenum: 786,
    megaStone: { Girafarig: "Girafarig-Mega" },
    num: 973,
    gen: 6,
    isNonstandard: "Past",
  },
  feraligatite: {
    name: "Feraligatite",
    spritenum: 788,
    megaStone: { Feraligatr: "Feraligatr-Mega" },
    num: 945,
    gen: 6,
    isNonstandard: "Past",
  },
  flygonarmor: {
    name: "Flygon Armor",
    spritenum: 789,
    forcedForme: "Flygon-Armor",
    num: 933,
    gen: 6,
  },
  flygonite: {
    name: "Flygonite",
    spritenum: 790,
    megaStone: { Flygon: "Flygon-Mega" },
    num: 946,
    gen: 6,
    isNonstandard: "Past",
  },
  froslassite: {
    name: "Froslassite",
    spritenum: 791,
    megaStone: { Froslass: "Froslass-Mega" },
    num: 947,
    gen: 6,
    isNonstandard: "Past",
  },
  gothitite: {
    name: "Gothitite",
    spritenum: 792,
    megaStone: { Gothitelle: "Gothitelle-Mega" },
    num: 948,
    gen: 6,
    isNonstandard: "Past",
  },
  haxorite: {
    name: "Haxorite",
    spritenum: 793,
    megaStone: { Haxorus: "Haxorus-Mega" },
    num: 949,
    gen: 6,
    isNonstandard: "Past",
  },
  hydreigonite: {
    name: "Hydreigonite",
    spritenum: 794,
    megaStone: { Hydreigon: "Hydreigon-Mega-Five" },
    num: 950,
    gen: 6,
    isNonstandard: "Past",
  },
  jirachite: {
    name: "Jirachite",
    spritenum: 795,
    megaStone: { Jirachi: "Jirachi-Mega" },
    num: 951,
    gen: 6,
    isNonstandard: "Past",
  },
  leavannyarmor: {
    name: "Leavanny Armor",
    spritenum: 796,
    forcedForme: "Leavanny-Armor",
    num: 933,
    gen: 6,
  },
  magcargonite: {
    name: "Magcargonite",
    spritenum: 797,
    megaStone: { Magcargo: "Magcargo-Mega" },
    num: 952,
    gen: 6,
    isNonstandard: "Past",
  },
  marowite: {
    name: "Marowite",
    spritenum: 798,
    megaStone: { Marowak: "Marowak-Mega" },
    num: 953,
    gen: 6,
    isNonstandard: "Past",
  },
  meganiumite: {
    name: "Meganiumite",
    spritenum: 799,
    megaStone: { Meganium: "Meganium-Mega" },
    num: 954,
    gen: 6,
    isNonstandard: "Past",
  },
  mewtwoarmor: {
    name: "Mewtwo Armor",
    spritenum: 800,
    forcedForme: "Mewtwo-Armor",
    num: 937,
    gen: 6,
  },
  milotite: {
    name: "Milotite",
    spritenum: 801,
    megaStone: { Milotic: "Milotic-Mega" },
    num: 955,
    gen: 6,
    isNonstandard: "Past",
  },
  miltankite: {
    name: "Miltankite",
    spritenum: 802,
    megaStone: { Miltank: "Miltank-Mega" },
    num: 956,
    gen: 6,
    isNonstandard: "Past",
  },
  nocturneincense: {
    name: "Nocturne Incense",
    spritenum: 803,
    num: 996,
    gen: 6,
  },
  nuzlockeball: {
    name: "Nuzlocke Ball",
    spritenum: 804,
    num: 997,
    gen: 6,
    isPokeball: true,
  },
  politoedite: {
    name: "Politoedite",
    spritenum: 805,
    megaStone: { Politoed: "Politoed-Mega" },
    num: 957,
    gen: 6,
    isNonstandard: "Past",
  },
  poliwrathite: {
    name: "Poliwrathite",
    spritenum: 806,
    megaStone: { Poliwrath: "Poliwrath-Mega" },
    num: 677,
    gen: 6,
    isNonstandard: "Past",
  },
  reuniclite: {
    name: "Reuniclite",
    spritenum: 807,
    megaStone: { Reuniclus: "Reuniclus-Mega" },
    num: 959,
    gen: 6,
    isNonstandard: "Past",
  },
  shadowmewtwonite: {
    name: "Shadow Mewtwonite",
    spritenum: 625,
    megaStone: { "Mewtwo-Shadow": "Mewtwo-Shadow-Mega" },
    num: 991,
    gen: 6,
    isNonstandard: "Past",
  },
  shiftrite: {
    name: "Shiftrite",
    spritenum: 808,
    megaStone: { Shiftry: "Shiftry-Mega" },
    num: 960,
    gen: 6,
    isNonstandard: "Past",
  },
  shinyball: {
    name: "Shiny Ball",
    spritenum: 809,
    num: 998,
    gen: 6,
    isPokeball: true,
  },
  snoreball: {
    name: "Snore Ball",
    spritenum: 810,
    num: 999,
    gen: 6,
    isPokeball: true,
  },
  spiritombite: {
    name: "Spiritombite",
    spritenum: 811,
    megaStone: { Spiritomb: "Spiritomb-Mega" },
    num: 961,
    gen: 6,
    isNonstandard: "Past",
  },
  steelixitesteel: {
    name: "Steelixite Steel",
    spritenum: 621,
    megaStone: { Steelix: "Steelix-Mega-Steel" },
    num: 761,
    gen: 6,
    isNonstandard: "Past",
  },
  steelixitefire: {
    name: "Steelixite Fire",
    spritenum: 812,
    megaStone: { Steelix: "Steelix-Mega-Fire" },
    num: 962,
    gen: 6,
    isNonstandard: "Past",
  },
  stunfiskite: {
    name: "Stunfiskite",
    spritenum: 813,
    megaStone: { Stunfisk: "Stunfisk-Mega" },
    num: 963,
    gen: 6,
    isNonstandard: "Past",
  },
  sudowoodite: {
    name: "Sudowoodite",
    spritenum: 814,
    megaStone: { Sudowoodo: "Sudowoodo-Mega" },
    num: 964,
    gen: 6,
    isNonstandard: "Past",
  },
  sunflorite: {
    name: "Sunflorite",
    spritenum: 815,
    megaStone: { Sunflora: "Sunflora-Mega-M" },
    num: 965,
    gen: 6,
    isNonstandard: "Past",
  },
  trickrock: {
    name: "Trick Rock",
    spritenum: 816,
    num: 928,
    gen: 6,
  },
  typhlosionite: {
    name: "Typhlosionite",
    spritenum: 817,
    megaStone: { Typhlosion: "Typhlosion-Mega" },
    num: 966,
    gen: 6,
    isNonstandard: "Past",
  },
  tyranitararmor: {
    name: "Tyranitar Armor",
    spritenum: 818,
    forcedForme: "Tyranitar-Armor",
    num: 932,
    gen: 6,
  },
  volcaronadeltaarmor: {
    name: "Volcarona-Delta Armor",
    spritenum: 819,
    forcedForme: "Volcarona-Delta-Armor",
    num: 936,
    gen: 6,
  },
  zebstrikite: {
    name: "Zebstrikite",
    spritenum: 820,
    megaStone: { Zebstrika: "Zebstrika-Mega" },
    num: 967,
    gen: 6,
    isNonstandard: "Past",
  },
  zekromarmor: {
    name: "Zekrom Armor",
    spritenum: 821,
    forcedForme: "Zekrom-Armor",
    num: 935,
    gen: 6,
  },
  zoronite: {
    name: "Zoronite",
    spritenum: 822,
    megaStone: { Zoroark: "Zoroark-Mega" },
    num: 968,
    gen: 6,
    isNonstandard: "Past",
  },
};
