import type { ModdedItemDataTable } from "@pkmn/sim";

export const Items: ModdedItemDataTable = {
  ancientball: {
    name: "Ancient Ball",
    spritenum: 752,
    num: 994,
    gen: 6,
    isPokeball: true,
  },
  bisharpite: {
    name: "Bisharpite",
    spritenum: 753,
    megaStone: "Bisharp-Mega",
    megaEvolves: "Bisharp",
    num: 992,
    gen: 6,
    isNonstandard: "Past",
  },
  cacturnite: {
    name: "Cacturnite",
    spritenum: 754,
    megaStone: "Cacturne-Mega",
    megaEvolves: "Cacturne",
    num: 938,
    gen: 6,
    isNonstandard: "Past",
  },
  chatotite: {
    name: "Chatotite",
    spritenum: 755,
    megaStone: "Chatot-Mega",
    megaEvolves: "Chatot",
    num: 939,
    gen: 6,
    isNonstandard: "Past",
  },
  crawdite: {
    name: "Crawdite",
    spritenum: 756,
    megaStone: "Crawdaunt-Mega",
    megaEvolves: "Crawdaunt",
    num: 940,
    gen: 6,
    isNonstandard: "Past",
  },
  cryogonite: {
    name: "Cryogonite",
    spritenum: 757,
    megaStone: "Cryogonal-Mega",
    megaEvolves: "Cryogonal",
    num: 941,
    gen: 6,
    isNonstandard: "Past",
  },
  crystalfragment: {
    name: "Crystal Fragment",
    spritenum: 758,
    megaStone: "Metagross-Delta-R-Crystal",
    megaEvolves: "Metagross-Delta-R",
    num: 993,
    gen: 6,
    isNonstandard: "Past",
  },
  crystalpiece: {
    name: "Crystal Piece",
    spritenum: 759,
    num: 929,
    gen: 6,
    isNonstandard: "Past",
  },
  darkrock: {
    name: "Dark Rock",
    spritenum: 760,
    num: 927,
    gen: 6,
  },
  deltaball: {
    name: "Delta Ball",
    spritenum: 761,
    num: 995,
    gen: 6,
    isPokeball: true,
  },
  deltabisharpite: {
    name: "Delta Bisharpite",
    spritenum: 762,
    megaStone: "Bisharp-Delta-Mega",
    megaEvolves: "Bisharp-Delta",
    num: 969,
    gen: 6,
    isNonstandard: "Past",
  },
  deltablastoisinite: {
    name: "Delta Blastoisinite",
    spritenum: 763,
    megaStone: "Blastoise-Delta-Mega",
    megaEvolves: "Blastoise-Delta",
    num: 970,
    gen: 6,
    isNonstandard: "Past",
  },
  deltacameruptite: {
    name: "Delta Cameruptite",
    spritenum: 764,
    megaStone: "Camerupt-Delta-Mega",
    megaEvolves: "Camerupt-Delta",
    num: 971,
    gen: 6,
    isNonstandard: "Past",
  },
  deltacharizardite: {
    name: "Delta Charizardite",
    spritenum: 765,
    megaStone: "Charizard-Delta-Mega",
    megaEvolves: "Charizard-Delta",
    num: 972,
    gen: 6,
    isNonstandard: "Past",
  },
  deltaetigirafarigite: {
    name: "Delta Etigirafarigite",
    spritenum: 766,
    megaStone: "Girafarig-Delta-Mega",
    megaEvolves: "Girafarig-Delta",
    num: 973,
    gen: 6,
    isNonstandard: "Past",
  },
  deltafroslassite: {
    name: "Delta Froslassite",
    spritenum: 767,
    megaStone: "Froslass-Delta-Mega",
    megaEvolves: "Froslass-Delta",
    num: 974,
    gen: 6,
    isNonstandard: "Past",
  },
  deltagalladite: {
    name: "Delta Galladite",
    spritenum: 768,
    megaStone: "Gallade-Delta-Mega",
    megaEvolves: "Gallade-Delta",
    num: 975,
    gen: 6,
    isNonstandard: "Past",
  },
  deltagardevoirite: {
    name: "Delta Gardevoirite",
    spritenum: 769,
    megaStone: "Gardevoir-Delta-Mega",
    megaEvolves: "Gardevoir-Delta",
    num: 976,
    gen: 6,
    isNonstandard: "Past",
  },
  deltaglalitite: {
    name: "Delta Glalitite",
    spritenum: 770,
    megaStone: "Glalie-Delta-Mega",
    megaEvolves: "Glalie-Delta",
    num: 977,
    gen: 6,
    isNonstandard: "Past",
  },
  deltalopunnite: {
    name: "Delta Lopunnite",
    spritenum: 771,
    megaStone: "Lopunny-Delta-Mega",
    megaEvolves: "Lopunny-Delta",
    num: 978,
    gen: 6,
    isNonstandard: "Past",
  },
  deltalucarionite: {
    name: "Delta Lucarionite",
    spritenum: 772,
    megaStone: "Lucario-Delta-Mega",
    megaEvolves: "Lucario-Delta",
    num: 979,
    gen: 6,
    isNonstandard: "Past",
  },
  deltamawilite: {
    name: "Delta Mawilite",
    spritenum: 773,
    megaStone: "Mawile-Delta-Mega",
    megaEvolves: "Mawile-Delta",
    num: 980,
    gen: 6,
    isNonstandard: "Past",
  },
  deltamedichamite: {
    name: "Delta Medichamite",
    spritenum: 774,
    megaStone: "Medicham-Delta-Mega",
    megaEvolves: "Medicham-Delta",
    num: 981,
    gen: 6,
    isNonstandard: "Past",
  },
  deltametagrossiteruin: {
    name: "Delta Metagrossite Ruin",
    spritenum: 775,
    megaStone: "Metagross-Delta-R-Mega",
    megaEvolves: "Metagross-Delta-R",
    num: 982,
    gen: 6,
    isNonstandard: "Past",
  },
  deltametagrossitespider: {
    name: "Delta Metagrossite Spider",
    spritenum: 776,
    megaStone: "Metagross-Delta-S-Mega",
    megaEvolves: "Metagross-Delta-S",
    num: 983,
    gen: 6,
    isNonstandard: "Past",
  },
  deltamilotite: {
    name: "Delta Milotite",
    spritenum: 777,
    megaStone: "Milotic-Delta-Mega",
    megaEvolves: "Milotic-Delta",
    num: 984,
    gen: 6,
    isNonstandard: "Past",
  },
  deltapidgeotite: {
    name: "Delta Pidgeotite",
    spritenum: 778,
    megaStone: "Pidgeot-Delta-Mega",
    megaEvolves: "Pidgeot-Delta",
    num: 985,
    gen: 6,
    isNonstandard: "Past",
  },
  deltasablenite: {
    name: "Delta Sablenite",
    spritenum: 779,
    megaStone: "Sableye-Delta-Mega",
    megaEvolves: "Sableye-Delta",
    num: 986,
    gen: 6,
    isNonstandard: "Past",
  },
  deltascizorite: {
    name: "Delta Scizorite",
    spritenum: 780,
    megaStone: "Scizor-Delta-Mega",
    megaEvolves: "Scizor-Delta",
    num: 987,
    gen: 6,
    isNonstandard: "Past",
  },
  deltasunflorite: {
    name: "Delta Sunflorite",
    spritenum: 781,
    megaStone: "Sunflora-Delta-Mega",
    megaEvolves: "Sunflora-Delta",
    num: 988,
    gen: 6,
    isNonstandard: "Past",
  },
  deltatyphlosionite: {
    name: "Delta Typhlosionite",
    spritenum: 782,
    megaStone: "Typhlosion-Delta-Mega",
    megaEvolves: "Typhlosion-Delta",
    num: 989,
    gen: 6,
    isNonstandard: "Past",
  },
  deltavenusaurite: {
    name: "Delta Venusaurite",
    spritenum: 783,
    megaStone: "Venusaur-Delta-Mega",
    megaEvolves: "Venusaur-Delta",
    num: 990,
    gen: 6,
    isNonstandard: "Past",
  },
  donphanite: {
    name: "Donphanite",
    spritenum: 784,
    megaStone: "Donphan-Mega",
    megaEvolves: "Donphan",
    num: 965,
    gen: 6,
    isNonstandard: "Past",
  },
  eevite: {
    name: "Eevite",
    spritenum: 785,
    megaStone: "Eevee-Mega-Base",
    megaEvolves: "Eevee-Pre-Mega",
    num: 973,
    gen: 6,
    isNonstandard: "Past",
  },
  etigirafarigite: {
    name: "Etigirafarigite",
    spritenum: 786,
    megaStone: "Girafarig-Mega",
    megaEvolves: "Girafarig",
    num: 973,
    gen: 6,
    isNonstandard: "Past",
  },
  feraligatite: {
    name: "Feraligatite",
    spritenum: 788,
    megaStone: "Feraligatr-Mega",
    megaEvolves: "Feraligatr",
    num: 945,
    gen: 6,
    isNonstandard: "Past",
  },
  flygonarmor: {
    name: "Flygon Armor",
    spritenum: 789,
    forcedForme: "Flygon-Armor",
    num: 933,
    gen: 6,
  },
  flygonite: {
    name: "Flygonite",
    spritenum: 790,
    megaStone: "Flygon-Mega",
    megaEvolves: "Flygon",
    num: 946,
    gen: 6,
    isNonstandard: "Past",
  },
  froslassite: {
    name: "Froslassite",
    spritenum: 791,
    megaStone: "Froslass-Mega",
    megaEvolves: "Froslass",
    num: 947,
    gen: 6,
    isNonstandard: "Past",
  },
  gothitite: {
    name: "Gothitite",
    spritenum: 792,
    megaStone: "Gothitelle-Mega",
    megaEvolves: "Gothitelle",
    num: 948,
    gen: 6,
    isNonstandard: "Past",
  },
  haxorite: {
    name: "Haxorite",
    spritenum: 793,
    megaStone: "Haxorus-Mega",
    megaEvolves: "Haxorus",
    num: 949,
    gen: 6,
    isNonstandard: "Past",
  },
  hydreigonite: {
    name: "Hydreigonite",
    spritenum: 794,
    megaStone: "Hydreigon-Mega-Five",
    megaEvolves: "Hydreigon",
    num: 950,
    gen: 6,
    isNonstandard: "Past",
  },
  jirachite: {
    name: "Jirachite",
    spritenum: 795,
    megaStone: "Jirachi-Mega",
    megaEvolves: "Jirachi",
    num: 951,
    gen: 6,
    isNonstandard: "Past",
  },
  leavannyarmor: {
    name: "Leavanny Armor",
    spritenum: 796,
    forcedForme: "Leavanny-Armor",
    num: 933,
    gen: 6,
  },
  magcargonite: {
    name: "Magcargonite",
    spritenum: 797,
    megaStone: "Magcargo-Mega",
    megaEvolves: "Magcargo",
    num: 952,
    gen: 6,
    isNonstandard: "Past",
  },
  marowite: {
    name: "Marowite",
    spritenum: 798,
    megaStone: "Marowak-Mega",
    megaEvolves: "Marowak",
    num: 953,
    gen: 6,
    isNonstandard: "Past",
  },
  meganiumite: {
    name: "Meganiumite",
    spritenum: 799,
    megaStone: "Meganium-Mega",
    megaEvolves: "Meganium",
    num: 954,
    gen: 6,
    isNonstandard: "Past",
  },
  mewtwoarmor: {
    name: "Mewtwo Armor",
    spritenum: 800,
    forcedForme: "Mewtwo-Armor",
    num: 937,
    gen: 6,
  },
  milotite: {
    name: "Milotite",
    spritenum: 801,
    megaStone: "Milotic-Mega",
    megaEvolves: "Milotic",
    num: 955,
    gen: 6,
    isNonstandard: "Past",
  },
  miltankite: {
    name: "Miltankite",
    spritenum: 802,
    megaStone: "Miltank-Mega",
    megaEvolves: "Miltank",
    num: 956,
    gen: 6,
    isNonstandard: "Past",
  },
  nocturneincense: {
    name: "Nocturne Incense",
    spritenum: 803,
    num: 996,
    gen: 6,
  },
  nuzlockeball: {
    name: "Nuzlocke Ball",
    spritenum: 804,
    num: 997,
    gen: 6,
    isPokeball: true,
  },
  politoedite: {
    name: "Politoedite",
    spritenum: 805,
    megaStone: "Politoed-Mega",
    megaEvolves: "Politoed",
    num: 957,
    gen: 6,
    isNonstandard: "Past",
  },
  poliwrathite: {
    name: "Poliwrathite",
    spritenum: 806,
    megaStone: "Poliwrath-Mega",
    megaEvolves: "Poliwrath",
    num: 677,
    gen: 6,
    isNonstandard: "Past",
  },
  reuniclite: {
    name: "Reuniclite",
    spritenum: 807,
    megaStone: "Reuniclus-Mega",
    megaEvolves: "Reuniclus",
    num: 959,
    gen: 6,
    isNonstandard: "Past",
  },
  shadowmewtwonite: {
    name: "Shadow Mewtwonite",
    spritenum: 625,
    megaStone: "Mewtwo-Shadow-Mega",
    megaEvolves: "Mewtwo-Shadow",
    num: 991,
    gen: 6,
    isNonstandard: "Past",
  },
  shiftrite: {
    name: "Shiftrite",
    spritenum: 808,
    megaStone: "Shiftry-Mega",
    megaEvolves: "Shiftry",
    num: 960,
    gen: 6,
    isNonstandard: "Past",
  },
  shinyball: {
    name: "Shiny Ball",
    spritenum: 809,
    num: 998,
    gen: 6,
    isPokeball: true,
  },
  snoreball: {
    name: "Snore Ball",
    spritenum: 810,
    num: 999,
    gen: 6,
    isPokeball: true,
  },
  spiritombite: {
    name: "Spiritombite",
    spritenum: 811,
    megaStone: "Spiritomb-Mega",
    megaEvolves: "Spiritomb",
    num: 961,
    gen: 6,
    isNonstandard: "Past",
  },
  steelixitesteel: {
    name: "Steelixite Steel",
    spritenum: 621,
    megaStone: "Steelix-Mega-Steel",
    megaEvolves: "Steelix",
    num: 761,
    gen: 6,
    isNonstandard: "Past",
  },
  steelixitefire: {
    name: "Steelixite Fire",
    spritenum: 812,
    megaStone: "Steelix-Mega-Fire",
    megaEvolves: "Steelix",
    num: 962,
    gen: 6,
    isNonstandard: "Past",
  },
  stunfiskite: {
    name: "Stunfiskite",
    spritenum: 813,
    megaStone: "Stunfisk-Mega",
    megaEvolves: "Stunfisk",
    num: 963,
    gen: 6,
    isNonstandard: "Past",
  },
  sudowoodite: {
    name: "Sudowoodite",
    spritenum: 814,
    megaStone: "Sudowoodo-Mega",
    megaEvolves: "Sudowoodo",
    num: 964,
    gen: 6,
    isNonstandard: "Past",
  },
  sunflorite: {
    name: "Sunflorite",
    spritenum: 815,
    megaStone: "Sunflora-Mega-M",
    megaEvolves: "Sunflora",
    num: 965,
    gen: 6,
    isNonstandard: "Past",
  },
  trickrock: {
    name: "Trick Rock",
    spritenum: 816,
    num: 928,
    gen: 6,
  },
  typhlosionite: {
    name: "Typhlosionite",
    spritenum: 817,
    megaStone: "Typhlosion-Mega",
    megaEvolves: "Typhlosion",
    num: 966,
    gen: 6,
    isNonstandard: "Past",
  },
  tyranitararmor: {
    name: "Tyranitar Armor",
    spritenum: 818,
    forcedForme: "Tyranitar-Armor",
    num: 932,
    gen: 6,
  },
  volcaronadeltaarmor: {
    name: "Volcarona-Delta Armor",
    spritenum: 819,
    forcedForme: "Volcarona-Delta-Armor",
    num: 936,
    gen: 6,
  },
  zebstrikite: {
    name: "Zebstrikite",
    spritenum: 820,
    megaStone: "Zebstrika-Mega",
    megaEvolves: "Zebstrika",
    num: 967,
    gen: 6,
    isNonstandard: "Past",
  },
  zekromarmor: {
    name: "Zekrom Armor",
    spritenum: 821,
    forcedForme: "Zekrom-Armor",
    num: 935,
    gen: 6,
  },
  zoronite: {
    name: "Zoronite",
    spritenum: 822,
    megaStone: "Zoroark-Mega",
    megaEvolves: "Zoroark",
    num: 968,
    gen: 6,
    isNonstandard: "Past",
  },
};
