import type { ModdedMoveDataTable } from "@pkmn/sim";

export const Moves: ModdedMoveDataTable = {
  achillesheel: {
    num: 1,
    accuracy: 100,
    basePower: 45,
    category: "Physical",
    name: "Achilles Heel",
    pp: 15,
    priority: 0,
    flags: {
      contact: 1,
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Normal",
    contestType: "Clever",
  },
  ancientroar: {
    num: 2,
    accuracy: 100,
    basePower: 80,
    category: "Special",
    name: "Ancient Roar",
    pp: 15,
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
      sound: 1,
      bypasssub: 1,
    },
    target: "normal",
    type: "Rock",
    contestType: "Cool",
  },
  corrode: {
    num: 3,
    accuracy: 100,
    basePower: 70,
    category: "Special",
    name: "Corrode",
    pp: 10,
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
    },
    target: "allAdjacent",
    type: "Poison",
    contestType: "Beautiful",
  },
  crystalrush: {
    num: 4,
    accuracy: 100,
    basePower: 45,
    category: "Physical",
    name: "Crystal Rush",
    pp: 30,
    priority: 1,
    flags: {
      contact: 1,
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Crystal",
    contestType: "Cool",
  },
  darkmatter: {
    num: 5,
    accuracy: 90,
    basePower: 150,
    category: "Special",
    name: "Dark Matter",
    pp: 5,
    priority: 0,
    flags: {
      recharge: 1,
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Dark",
    contestType: "Cool",
  },
  dracojet: {
    num: 6,
    accuracy: 100,
    basePower: 40,
    category: "Physical",
    name: "Draco Jet",
    pp: 20,
    priority: 1,
    flags: {
      contact: 1,
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Dragon",
    contestType: "Cool",
  },
  dragonify: {
    num: 7,
    accuracy: 100,
    basePower: 0,
    category: "Status",
    name: "Dragonify",
    pp: 20,
    priority: 0,
    flags: {
      protect: 1,
      reflectable: 1,
      mirror: 1,
      allyanim: 1,
    },
    target: "normal",
    type: "Dragon",
    contestType: "Cute",
  },
  drakonvoice: {
    num: 8,
    accuracy: 85,
    basePower: 105,
    category: "Special",
    name: "Drakon Voice",
    pp: 10,
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
      sound: 1,
      bypasssub: 1,
    },
    target: "allAdjacentFoes",
    type: "Dragon",
    contestType: "Tough",
  },
  jetstream: {
    num: 9,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Jet Stream",
    pp: 30,
    priority: 0,
    flags: {
      snatch: 1,
      wind: 1,
    },
    sideCondition: "jetstream",
    target: "allySide",
    type: "Dragon",
  },
  livewire: {
    num: 10,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Livewire",
    pp: 20,
    priority: 0,
    flags: {
      reflectable: 1,
      nonsky: 1,
    },
    sideCondition: "livewire",
    target: "foeSide",
    type: "Electric",
    contestType: "Clever",
  },
  lunarcannon: {
    num: 11,
    accuracy: 100,
    basePower: 105,
    category: "Special",
    name: "Lunar Cannon",
    pp: 10,
    priority: 0,
    flags: {
      charge: 1,
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Dark",
    contestType: "Cool",
  },
  medusaray: {
    num: 12,
    accuracy: 100,
    basePower: 0,
    category: "Status",
    name: "Medusa Ray",
    pp: 20,
    priority: 0,
    flags: {
      protect: 1,
      reflectable: 1,
      mirror: 1,
      allyanim: 1,
    },
    target: "normal",
    type: "Rock",
    contestType: "Cute",
  },
  morph: {
    num: 650,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Morph",
    pp: 10,
    priority: 0,
    flags: {
      allyanim: 1,
    },
    target: "normal",
    type: "Normal",
    contestType: "Clever",
  },
  nanorepair: {
    num: 13,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Nanorepair",
    pp: 5,
    priority: 0,
    flags: {
      snatch: 1,
      heal: 1,
    },
    target: "self",
    type: "Steel",
    contestType: "Cute",
  },
  newmoon: {
    num: 14,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "New Moon",
    pp: 5,
    priority: 0,
    flags: {},
    weather: "NewMoon",
    target: "all",
    type: "Dark",
    contestType: "Beautiful",
  },
  permafrost: {
    num: 15,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Permafrost",
    pp: 15,
    priority: 0,
    flags: {
      reflectable: 1,
      nonsky: 1,
    },
    sideCondition: "permafrost",
    target: "foeSide",
    type: "Ice",
    contestType: "Clever",
  },
  retrograde: {
    num: 700,
    accuracy: 100,
    basePower: 0,
    category: "Status",
    name: "Retrograde",
    pp: 30,
    priority: 0,
    flags: {
      allyanim: 1,
    },
    target: "normal",
    type: "Normal",
    contestType: "Clever",
  },
  spiritaway: {
    num: 16,
    accuracy: 100,
    basePower: 100,
    category: "Physical",
    name: "Spirit Away",
    pp: 5,
    priority: 0,
    flags: {
      contact: 1,
      charge: 1,
      protect: 1,
      mirror: 1,
      distance: 1,
    },
    target: "normal",
    type: "Fairy",
    contestType: "Tough",
  },
  stealthcoal: {
    num: 798,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Stealth Coal",
    pp: 20,
    priority: 0,
    flags: {
      reflectable: 1,
    },
    sideCondition: "stealthcoal",
    target: "foeSide",
    type: "Fire",
    contestType: "Cool",
  },
  wormhole: {
    num: 18,
    accuracy: 100,
    basePower: 40,
    category: "Special",
    name: "Wormhole",
    pp: 30,
    priority: 1,
    flags: {
      protect: 1,
      mirror: 1,
    },
    target: "normal",
    type: "Psychic",
    contestType: "Cool",
  },
  zombiestrike: {
    num: 570,
    accuracy: 90,
    basePower: 90,
    category: "Physical",
    name: "Zombie Strike",
    pp: 15,
    priority: 0,
    flags: {
      contact: 1,
      protect: 1,
    },
    target: "normal",
    type: "Ghost",
  },
};
